### ISSUE TITLE
Whip it like a nascar, I can see the time pass

### ISSUE THREAD

**Issue by Multimegamander** [DS-Homebrew/ds-homebrew.github.io#1]

**Comment by NightYoshi370** [comment]
Please contribute something meaningful instead of spamming.

**Comment by RocketRobz** [comment]
There should be a feature that deletes an issue.
It's below `Transfer issue`.

**Comment by NightYoshi370** [comment]
Doesn't appear for me
![image](https://user-images.githubusercontent.com/18664762/52607869-bf093080-2e2c-11e9-80e0-9c6f74c85186.png)
